-- Criando Tabela Entrega --
CREATE TABLE ENTREGA
(
	ID	TINYINT IDENTITY (1,1) NOT NULL,
	IDALUNO TINYINT NOT NULL,
	IDATIVIDADEVINCULADA TINYINT  NOT NULL,
	TITULO VARCHAR(200) NOT NULL,
	RESPOSTA CHAR(1000) NOT NULL,
	DTENTREGA DATETIME NOT NULL  DEFAULT(GETDATE()),
	STATUS VARCHAR(50) NOT NULL DEFAULT('ENTREGUE'),
	IDPROFESSOR TINYINT,
	NOTA NUMERIC(10,2),
	DTAVALIAÇÃO	DATETIME,
	OBS CHAR(500),

	CONSTRAINT PK_ENTREGA PRIMARY KEY(ID),
	--CONSTRAINT DF_DTENTREGA DEFAULT(GETDATE()) FOR DTENTREGA,
	--CONSTRAINT DF_STATUS DEFAULT('ENTREGUE') FOR STATUS,
	CONSTRAINT CK_CKSTATUS
				CHECK(STATUS IN ('ENTREGUE','CORRIGIDO')),
	CONSTRAINT CK_CKNOTA
				CHECK(NOTA >= 0 AND NOTA <= 10)
);
	-- Criando Tabela Mensagem--
CREATE TABLE MENSAGEM(
	ID	TINYINT IDENTITY (1,1) NOT NULL,
	IDALUNO	TINYINT  NOT NULL,
	IDPROFESSOR	TINYINT  NOT NULL,
	ASSUNTO	VARCHAR(100) NOT NULL,
	REFERENCIA CHAR(1000) NOT NULL,
	CONTEUDO VARCHAR(200) NOT NULL,
	STATUS VARCHAR(50) NOT NULL DEFAULT('ENVIADO'),
	DTENVIO DATETIME NOT NULL DEFAULT(GETDATE()),
	DTRESPOSTA	DATETIME,
	RESPOSTA CHAR(500),

	--CONSTRAINT DF_STATUS DEFAULT('ENVIADO') FOR STATUS,
	CONSTRAINT CK_CKSTATUS1
				CHECK(STATUS IN ('ENVIADO','LIDO','RESPONDIDO'))
	
);
