	-- USUARIO
INSERT INTO USUARIO (LOGIN, SENHA) VALUES
('GILSON.ALMEIDA','G1501375'),
('SEBASTIAO.RODRIGUES','S1602440'),
('VALDIR.CASTRO','V1602396'),
('LUIZ.MELO','L1701777'),
('FRANCISCO.JESUS','F1602405'),
('NELSON.MOREIRA','N1602128'),
('RAIMUNDO.MORAE','R1602230'),
('FABIO.MOURA','F1601249'),
('ANDRE.COSTA','A1701595'),
('MARCIO.BATISTA','M1601576'),
('VINICIUS.CONCEICAO','V1501550'),
('JOAO.SOUSA','J1702249'),
('ANTONIO.MAGALHAES','A1702525'),
('JOSE.MORAIS','J1501148'),
('JONATHAN.FILHO','J1502810'),
('PAULO.MELO','P1602770'),
('ALESSANDRO.DIAS','A1602697'),
('EVERTON.MARTINS','E1602173'),
('EDSON.FERNANDES','E1601713'),
('EMERSON.MENEZES','E1602326'),
('CICERO.SANTANA','C1501257'),
('MICHELE.GARCIA','M1501464'),
('DOUGLAS.XAVIER','D1502465'),
('RODRIGO.GOMES','R1502808'),
('ALEXANDRE.DIAS','A1601975'),
('MAURO.CARVALHO','M1702530'),
('EDUARDO.VIEIRA','E1602305'),
('FABRICIO.MACHADO','F1701582'),
('DANIEL.ROCHA','D1501352'),
('JEAN.NEVES','J1701910'),
('TAMIRES.CAVALCANTE','T1701166'),
('DIEGO.NETO','D1502850'),
('MARCELO.SANTOS','M1602346'),
('LEONARDO.CUNHA','L1601418'),
('ALAN.AGUIAR','A1702476'),
('ADRIANA.MACHADO','A1702619'),
('MARIA.NASCIMENTO','M1502116'),
('ANA.FARIAS','A1702648'),
('RENATA.COSTA','R1702436'),
('VERA.CARDOSO','V1602388'),
('ELIANE.MENDES','E1701548'),
('JESSICA.PEREIRA','J1502514'),
('PRISCILA.FARIAS','P1601584'),
('ROSANGELA.RIBEIRO','R1502845'),
('LUCIANA.FERREIRA','L1601609'),
('ELAINE.BRAGA','E1702717'),
('ANTONIA.FILHO','A1602719'),
('PATRICIA.MORAIS','P1601963'),
('MARIA.MORAES','M1602611'),
('CLAUDIA.MOURA','M1601449'),
('ALAN.OLIVEIRA', '12345678'),
('ALBERTO.JUNIOR', '12345678'),
('ALEXANDRE.RANGEL', '12345678'),
('ALEXANDRE.MARTINS', '12345678'),
('ALVARO.TAKEI', '12345678'),
('ANA.SANTOS', '12345678'),
('BRUNO.KALKEVICIUS', '12345678'),
('CEZAR.BELLINI', '12345678'),
('EDSON.SILVA', '12345678'),
('EDSON.TSUKIMOTO', '12345678'),
('EDUARDO.QUEIROZ', '12345678'),
('EMILIO.RESENDE', '12345678'),
('FELIPE.DIAS', '12345678'),
('FERNANDO.ZUHER', '12345678'),
('FRANCESCA.ROMANELLI', '12345678'),
('GISELDA.PEREIRA', '12345678'),
('GUILHERME.LOHMANN', '12345678'),
('GUSTAVO.FERREIRA', '12345678'),
('ILANA.CONCILIO', '12345678'),
('IZA.MEL�O', '12345678'),
('JOAO.COUTINHO', '12345678'),
('JOSE.PRADO', '12345678'),
('LEONARDO.TAKUNO', '12345678'),
('LUCAS.GON�ALVES', '12345678'),
('LUCIANO.CROCCO', '12345678'),
('MARCEL.PIRES', '12345678'),
('MARCELO.SILVA', '12345678'),
('MARCELO.TERRA', '12345678'),
('MAR�O.JEUNON', '12345678'),
('OSVALDO.TAKAI', '12345678'),
('PEDRO.PADRO', '12345678'),
('PL�NIO.FILHO', '12345678'),
('RENATO.SANTOS', '12345678'),
('RODRIGO.PIASSI', '12345678'),
('SERGIO.BRUZETTI', '12345678'),
('VANDERSON.BOSSI', '12345678'),
('VICTOR.OLIVEIRA', '12345678'),
('VLADIMIR.CHAGAS', '12345678'),
('BRUNO.LIMA','12345678'),
('ALLAN.CARVALHO','51834538'),
('AYAO.OKAMOTO','86757519'),
('MICHELLE.MESTRE','12347890'),
('ANDREA.COSTA','12345678');

	-- ALUNOS
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(1,'GILSON FERNANDES ALMEIDA','gf_almeida@impacta.com.br','9234131243','1501375');

INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(2,'SEBASTIAO DE OLIVEIRA RODRIGUES','sd_rodrigues@impacta.com.br','912344321','1602440');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(3,'VALDIR GOMES DE CASTRO','vg_castro@impacta.com.br','987655687','1602396');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(4,'LUIZ CARLOS DE JESUS MELO','ld_melo@impacta.com.br','912346321','1701777');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(5,'FRANCISCO DE SOUZA JESUS','fd_jesus@impacta.com.br','948639721','1602405');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(6,'NELSON FERREIRA DE MOREIRA','nf_moreira@impacta.com.br','964823197','1602128');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(7,'RAIMUNDO VIEIRA MORAES','rv_moraes@impacta.com.br','908974231','1602230');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(8,'FABIO FERNANDES MOURA','ff_moura@impacta.com.br','980974231','1601249');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(9,'ANDRE SANTOS DE COSTA','as_costa@impacta.com.br','910897423','1701595');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(10,'MARCIO DA COSTA BATISTA','md_batista@impacta.com.br','908974123','1601576');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(11,'VINICIUS SOUZA CONCEICAO','vs_conceicao@impacta.com.br','934289743','1501650');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(12,'JOAO BATISTA ALVES DA SOUSA','ja_sousa@impacta.com.br','9417829034','1702249');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(13,'ANTONIO CARLOS FERREIRA DE MAGALHAES','af_magalhaes@impacta.com.br','981234897','1702525');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(14,'JOSE CARLOS LIMA MORAIS','jl_morais@impacta.com.br','946123879','1501148');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(15,'JONATHAN SANTOS DE FILHO','js_filho@impacta.com.br','941632789','1502810');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(16,'PAULO RODRIGUES DA MELO','pr_melo@impacta.com.br','919283476','1602770');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(17,'ALESSANDRO  DIAS','a_dias@impacta.com.br','917234908','1602697');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(18,'EVERTON DE OLIVEIRA MARTINS','ed_martins@impacta.com.br','94618279','1602173');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(19,'EDSON APARECIDA DE FERNANDES','ea_fernandes@impacta.com.br','912346789','1601713');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(20,'EMERSON GOMES MENEZES','eg_menezes@impacta.com.br','946897231','1602326');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(21,'CICERO PEREIRA DE SANTANA','cp_santana@impacta.com.br','919283674','1501257');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(22,'MICHELE SOUZA GARCIA','ms_garcia@impacta.com.br','971234897','1501464');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(23,'DOUGLAS GONCALVES XAVIER','dg_xavier@impacta.com.br','942634897','1502465');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(24,'RODRIGO REGINA GOMES','rr_gomes@impacta.com.br','912376589','1502808');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(25,'ALEXANDRE DE JESUS DIAS','ad_dias@impacta.com.br','923419686','1601975');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(26,'MAURO DE JESUS CARVALHO','md_carvalho@impacta.com.br','943621789','1702530');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(27,'EDUARDO  VIEIRA','e_vieira@impacta.com.br','942135687','1602305');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(28,'FABRICIO REGINA MACHADO','fr_machado@impacta.com.br','941236789','1701582');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(29,'DANIEL FERREIRA DE ROCHA','df_rocha@impacta.com.br','9213467859','1501352');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(30,'JEAN DA COSTA NEVES','jd_neves@impacta.com.br','941236897','1701910');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(31,'TAMIRES PEREIRA DE CAVALCANTE','tp_cavalcante@impacta.com.br','952316897','1701166');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(32,'DIEGO REGINA NETO','dr_neto@impacta.com.br','941329867','1502850');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(33,'MARCELO DOS SANTOS','md_santos@impacta.com.br','941237896','1602346');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(34,'LEONARDO RODRIGUES DE CUNHA','lr_cunha@impacta.com.br','941285896','1601418');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(35,'ALAN ALVES AGUIAR','aa_aguiar@impacta.com.br','941237588','1702476');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(36,'ADRIANA FERNANDES MACHADO','af_machado@impacta.com.br','941236879','1702619');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(37,'MARIA BARBOSA NASCIMENTO','mb_nascimento@impacta.com.br','932714189','1502116');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(38,'ANA PAULA FERREIRA DE FARIAS','af_farias@impacta.com.br','942138976','1702648');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(39,'RENATA VIEIRA COSTA','rv_costa@impacta.com.br','914237698','1702436');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(40,'VERA  CARDOSO','v_cardoso@impacta.com.br','998761234','1602388');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(41,'ELIANE BARBOSA MENDES','eb_mendes@impacta.com.br','943215787','1701548');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(42,'JESSICA DE OLIVEIRA PEREIRA','jd_pereira@impacta.com.br','942318957','1502514');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(43,'PRISCILA MARIA DE FARIAS','pm_farias@impacta.com.br','998761423','1601584');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(44,'ROSANGELA PEREIRA DE RIBEIRO','rp_ribeiro@impacta.com.br','941237967','1502845');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(45,'LUCIANA MARIA FERREIRA','lm_ferreira@impacta.com.br','943278932','1601609');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(46,'ELAINE SOARES BRAGA','es_braga@impacta.com.br','912376893','1702717');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(47,'ANTONIA FERREIRA FILHO','af_filho@impacta.com.br','923167893','1602719');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(48,'PATRICIA DE SOUZA MORAIS','pd_morais@impacta.com.br','934216789','1601963');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(49,'MARIA JOSE APARECIDA MORAES','ma_moraes@impacta.com.br','974367892','1602611');

INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(50,'CLAUDIA DE LIMA MOURA','cd_moura@impacta.com.br','978365892','1601449');


	-- COORDENADOR
INSERT INTO COORDENADOR (IDUSUARIO, NOME, EMAIL, CELULAR)VALUES
	(65, 'FRANCESCA ROMANELLI', 'f_romanelli@impacta.com.br','11935612587'),
	(56, 'ANA CRISTINA DOS SANTOS','ac_santos@impacta.com.br','11965325167'),
	(89, 'BRUNO LUIS SOARES DE LIMA','b_lima@impacta.com.br','11965771258'),
	(80, 'OSVALDO KOTARO TAKAI','ok_takai@impacta.com.br','11963258147'),
	(90, 'ALAN HENRIQUE PARDO DE CARVALHO','al_carvalho@impacta.com.br','11965846576'),
	(91, 'AYAO OKAMOTO', 'ay_okamoto@impacta.com.br','11968541235');

	-- CURSOS
INSERT INTO CURSO(NOME) 
    VALUES ('Administra��o');

INSERT INTO CURSO(NOME) 
    VALUES ('An�lise e Desenvolvimento de Sistemas');

INSERT INTO CURSO(NOME) 
    VALUES ('An�lise e Desenvolvimento de Sistemas EAD');

INSERT INTO CURSO(NOME) 
    VALUES ('Banco de Dados');

INSERT INTO CURSO(NOME) 
    VALUES ('Engenharia da Computa��o');

INSERT INTO CURSO(NOME) 
    VALUES ('Gest�o de Tecnologia da Informa��o');

INSERT INTO CURSO(NOME) 
    VALUES ('Jogos Digitais');

INSERT INTO CURSO(NOME) 
    VALUES ('Processo Gerenciais');

INSERT INTO CURSO(NOME) 
    VALUES ('Produ��o de Multim�dia');

INSERT INTO CURSO(NOME) 
    VALUES ('Redes de Computadores');

INSERT INTO CURSO(NOME) 
    VALUES ('Sistema de Informa��o');

	-- DISCIPLINA
	-- OBSERVA��O!! O NOME CAMPO 'NOME' DEVE SER ALTERADO PARA VARCHAR(100), POIS H� MATERIAS QUE POSSUEM MAIS DE 30 CARACTERES, CASO CONTRARIO N�O EXECUTARA -- 

	-- ADMINISTR��O
INSERT INTO DISCIPLINA VALUES
	--  1SEM
	('Comunica��o e Express�o', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Fundamentos da Administra��o', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Macroeconomia', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Matem�tica Aplicada', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Modelos de Neg�cio e Empreendedorismo', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Pensamento Cr�tico e �tica', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	-- 2SEM
	('An�lise Explorat�ria de Dados', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('C�lculo', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Contabilidade Financeira', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Microeconomia', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Racioc�nio Anal�tico', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Sociologia e Pol�tica', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	-- 3SEM
	('Comportamento Organizacional', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Contabilidade Gerencial', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Gest�o de Projetos e Programas', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Intelig�ncia de Neg�cios', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Matem�tica Financeira', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Modelagem de Processos de Neg�cio', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	-- 4SEM
	('Administra��o Financeira', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Estrat�gia Organizacional', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Gest�o de Marketing', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Gest�o de Opera��es', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Gest�o Estrat�gica de Pessoas', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	-- 5SEM
	('Design Thinking', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Direito Aplicado � Administra��o', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Gest�o de Qualidade', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Marketing Avan�ado', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Responsabilidade Social Corporativo', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Startup e Inova��o', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	-- 6SEM
	('Finan�as Corporativas e Mercado de Capitais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Gest�o da Cadeia de Suprimentos', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Gest�o de Custos', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Gest�o de Projetos de Inova��o', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Tomada de Decis�o e Negocia��o', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	-- 7SEM
	('An�lise de Viabilidade de Projetos', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Estrat�gia Competitiva e Corporativa', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Jogos de Estrat�gias', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	
	-- 8SEM
	('Governan�a Corporativa', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Neg�cios Internacionais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Sistemas Integrados de Gest�o', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1);
	

	-- An�lise e Desenvolvimento de Sistemas
INSERT INTO DISCIPLINA VALUES
	-- 1SEM
	('Fundamentos de Banco de Dados', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Introdu��o � Internet das Coisas - IoT', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Linguagem de Programa��o I', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('L�gica de Programa��o', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	-- 2SEM
	('Linguagem de Programa��o II', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Linguagem SQL', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Tecnologia Web', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Engenharia de Software', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Gest�o de Projetos', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Ambiente de Desenvolvimento e Opera��o', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	-- 3SEM
	('Desenvolvimento de Aplica��es Distribu�daso', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Estrutura de Dados', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('An�lise e Modelagem de Sistemas', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Engenharia de Requisitos', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Interface Homem-Computador', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	-- 4SEM
	('Arquitetura e Projeto de Sistemas', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Desenvolvimento para Dispositivos M�veis', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Desenvolvimento para Internet das Coisas', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Qualidade de Software', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Legisla��o e �tica', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2);

	-- Sistemas de Informa��o
INSERT INTO DISCIPLINA VALUES 
	-- 5SEM
	('Business Agility', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 4),
	('Desenvolvimento de Sistemas de Informa��o', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 4),
	('Teoria da Computa��o', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 4),
	-- 6SEM
	('Integra��o e Desenvolvimento de Sistemas', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 4),
	-- 7SEM
	('Business Intelligence', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 4),
	('Seguran�a e Auditoria de Sistemas', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 4),
	('Gest�o de Infraestrutura de TI', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 4),
	-- 8SEM
	('Computa��o Cognitiva', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 4),
	('Governan�a de TI', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 4);

	-- Banco de Dados
INSERT INTO DISCIPLINA VALUES
	-- 2SEM
	('Desenvolvimento de Sistemas', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	-- 3SEM
	('Developing Database', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Data Analytics', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	-- 4SEM
	('Administra��o de Banco de Dados', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Qualidade de Governan�a de Dados', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Seguran�a de Banco de Dados', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Big Data', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2);

	-- Engenharia da Computa��o
INSERT INTO DISCIPLINA VALUES
	-- 1SEM
	('Circuitos Digitais e Eletr�nicos', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Matem�tica para Engenharia', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	-- 2SEM
	('Conceitos e Aplica��es de C�lculo', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	-- 3SEM
	('Ci�ncias do Ambiente', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Desenvolvimento de Aplica��es Distribu�das', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Modelagem e Simula��o de Sistemas F�sicos', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	-- 4SEM
	('Circuitos El�tricos', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Eletricidade e Magnetismo Aplicados', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Matem�tica Discreta', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Otimiza��o de Sistemas Lineares', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	-- 5SEM
	('An�lise Num�rica', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Arquitetura de Computadores e Sistemas Operacionais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	-- 6SEM
	('Compiladores', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Controle e Automa��o', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Gest�o �gil de Projetos', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Sistemas Distribu�dos e Cloud Computing', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	-- 7SEM
	('Economia para Engenharia', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Rob�s M�veis Inteligentes', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Seguran�a Cibern�tica', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('UX e Design Thinking', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	-- 8SEM
	('Ind�stria 4.0', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Projeto de Sistemas Embarcados', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Sistemas Tolerantes a Falhas', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('T�picos Especiais em Tend�ncias Tecnol�gicas', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3);

	-- Gest�o da Tecnologia da Informa��o
INSERT INTO DISCIPLINA VALUES
	('Gest�o Estrat�gica de TI', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 4);

	-- Jogos Digitais
INSERT INTO DISCIPLINA VALUES
	-- 
	('Desenho e Concept Art para Jogos', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Design de Jogos I', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Empreendedorismo', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Introdu��o aos Jogos Digitais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Arte 2D para Jogos Digitais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Arte 3D para Jogos Digitais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Design de Jogos II', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Programa��o para Jogos Digitais I', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Processo de Produ��o de Jogos Digitais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Game Level Design', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Design de Personagens para Jogos Digitais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Jogos Digitais para Web', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Programa��o para Jogos Digitais II', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Roteiriza��o e Storyboard para Jogos Digitais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Anima��o, �udio e V�deo para Jogos Digitais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Estudos Complementares em Jogos Digitais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Jogos Digitais para Dispositivos M�veis', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Marketing para Jogos Digitais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Qualidade e Testes para Jogos Digitais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5);

	-- Processos Gerenciais
INSERT INTO DISCIPLINA VALUES
	('Modelos de Neg�cios e Empreendedorismo', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1);

	-- Produ��o Multimidia
INSERT INTO DISCIPLINA VALUES
	('Teoria da Cor', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Filosofia', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Processo Criativo', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Storytelling', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Tipografia', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Computa��o Gr�fica', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Fotografia Digital', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Gamifica��o', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Novas M�dias', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Marketing Digital e M�dias Sociais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Cria��o e Produ��o Web', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Design de Informa��o', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Dire��o de Arte', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Modelagem 3D', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Produ��o Audiovisual', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Aplicativo Mobile', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Cibercultura', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Linguagem Sonora', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Efeitos Especiais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6);

	-- Redes de Computadores
INSERT INTO DISCIPLINA VALUES
	('Administra��o de Redes e Sistemas', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Cabeamento Estruturado:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Arquitetura de Redes de Computadores:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Fundamentos de Sistemas Operacionais:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Programa��o para Redes:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Administra��o de Redes e Sistemas Operacionais Livres:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Redes de Longa Dist�ncia:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Routing:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Seguran�a em Redes e Infraestrutura:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Comunica��o de Dados:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Diagn�stico e Gerenciamento de Redes:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Redes Convergentes:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Seguran�a em Sistemas:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Switching:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Computa��o em Nuvem:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Comunica��es M�veis:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Auditoria e Controle de TI:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Redes IPV6:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Servi�os de Redes de Computadores:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('T�picos Especiais em Redes de Computadores:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3);

	-- Outros
INSERT INTO DISCIPLINA VALUES
	('OPE1 - Oficina Projeto Empresa 1', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('OPE2 - Oficina Projeto Empresa 2', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('OPE3 - Oficina Projeto Empresa 3', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Sociedade e Sustentabilidade - Optativa', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Linguagem Brasileira de Sinais - LIBRAS', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Trabalho de Conclus�o de Curso 1 - TCC1', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Trabalho de Conclus�o de Curso 2 - TCC2', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1);

--Inserindo Professores na tabela Professor--

INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
VALUES(51,'ALAN ALVES DE OLIVEIRA','aa_oliveira@impacta.com.br','912345678','ALAN ')

INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
VALUES(52,'ALBERTO DE MEDEIROS JUNIOR','am_junior@impacta.com.br','923845967', 'ALBERTO')

INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(53,'ALEXANDRE LEITE RANGEL','al_rangel@impacta.com.br','943829748', 'RANGEL')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(54,'ALEXANDRE LOCCI MARTINS','al_martins@impacta.com.br','957394928','MARTINS')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(55,'ALVARO TOSHIO TAKEI','at_takei@impacta.com.br','947284927', 'ALVARO')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(56,'ANA CRISTINA DOS SANTOS','ac_santos@impacta.com.br','943829347','ANA ')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(57,'BRUNO ROBERTO KALKEVICIUS','br_kalkevicius@impacta.com.br','958329475', 'BRUNO')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(58,'CEZAR BELLINI','c_bellini@impacta.com.br','918475385', ' CEZAR')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(59,'EDSON BENITES SILVA','eb_silva@impacta.com.br','968492045', 'EDSON ')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(60,' EDSON TIHARU TSUKIMOTO','et_tsukimoto@impacta.com.br ',' 967894567', ' TSUKIMOTO')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(61,' EDUARDO LUIS DE QUEIROZ','el_queiroz@impacta.com.br ','978394756', ' EDU')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(62,' EMILIO MURTA RESENDE',' em_resende@impacta.com.br','934586923 ', 'EMILIO ')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(63,' FELIPE AUGUSTO ROCHA DIAS','fa_dias@impacta.com.br ','988334495 ', 'FELIPE ')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(64,' FERNANDO ZUHER','f_zuher@impacta.com.br ',' 974938540', 'FERNANDO ')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(65,'FRANCESCA ROMANELLI ','f_romanelli@impacta.com.br ','984726485 ', ' FRANCESCA')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(66,'GISELDA FERNANDA PEREIRA ','gf_pereira@impacta.com.br ','997840597', ' GISELDA')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(67,'GUILHERME GARCEZ LOHMANN ',' gg_lohmann@impacta.com.br','989485725 ', 'GUILHERME ')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(68,'GUSTAVO MENDES FERREIRA ',' gm_ferreira@impacta.com.br','909485736 ', 'FERREIRA ')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(69,'ILANA DE ALMEIDA SOUZA CONCILIO ',' ia_concilio@impacta.com.br','984756349 ', ' ILANA')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(70,' IZA MELÃO',' i_melão@impacta.com.br',' 985736450', ' IZA')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(71,' JOÃO PAULO VENÂNCIO COUTINHO','jp_coutinho@impacta.com.br ','9485722645 ', ' JP')
	 
	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(72,'JOSÉ PACHECO DE ALMEIDA PRADO',' jp_prado@impacta.com.br','995403900 ', ' PACHECO')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(73,'LEONARDO MASSAYUKI TAKUNO ',' lm_takuno@impacta.com.br','950693847 ', ' TAKUNO')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(74,' LUCAS MENDES MARQUES GONÇALVES',' lm_gonçalves@impacta.com.br','995006798 ', 'LUCAS ')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(75,' LUCIANO CROCCO','l_crocco@impacta.com.br ','955683499 ', 'LUCIANO ')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(76,'MARCEL GINOTTI PIRES ',' mg_pires@impacta.com.br',' 945069405', ' MARCEL')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(77,'MARCELO CORREIA DA SILVA','mc_silva@impacta.com.br','905948350','MARCELO')
	 
	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(78,'MARCELO SANSINI TERRA','ms_terra@impacta.com.br','909584739','SANSINI')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(79,'MARCO TÚLIO JEUNON','mt_jeunon@impacta.com.br','900948573','MARCO')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(80,'OSVALDO KOTARO TAKAI','ok_takai@impacta.com.br','958437567','TAKAI')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(81,'PEDRO FELIPE DO PRADO','pf_prado@impacta.com.br','905968374','PEDRO')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(82,'PLÍNIO BARBIERI FILHO','pb_filho@impacta.com.br','940583277','PLINIO')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(83,'RENATO DE SOUZA SANTOS','rs_santos@impacta.com.br','940593845','RENATO')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(84,'RODRIGO PIASSI','r_piassi@impacta.com.br','905943849','RODRIGO')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(85,'SÉRGIO EDUARDO DI SANTORO BRUZETTI','se_bruzetti@impacta.com.br','999504958','SÉRGIO')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(86,'VANDERSON GOMES BOSSI','vg_bossi@impacta.com.br','998574634','VANDERSON')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(87,'VICTOR INÁCIO DE OLIVEIRA','vi_oliveira@impacta.com.br','958439846','VICTOR')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(88,'VLADIMIR CHAGAS','v_chagas@impacta.com.br','905846372','VLADIMIR')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(92,'MICHELLE BRUNA BILECKI MESTRE','michelle.mestre@impacta.edu.br','907846372','MICHELLE')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(93,'ANDREA VOLANTE COSTA','andrea.costa@impacta.edu.br','907848372','ANDREA')

INSERT INTO DISCIPLINAOFERTADA(IDCOORDENADOR,DTINICIOMATRICULA,DTFIMMATRICULA,IDDISCIPLINA,IDCURSO,ANO,SEMESTRE,TURMA,IDPROFESSOR,METODOLOGIA,RECURSOS,CRITERIOAVALIACAO,PLANODEAULAS)
	--CURSO ADS
			--INSERÇÃO DICIPLINA AMBIENTE E DESENVOLVIMENTO E OPERAÇÕES - ADS
    VALUES  (2,'2018-08-04','2018-12-05',50,2,2018,2,'A',36,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(2,'2018-08-04','2018-12-05',50,2,2018,2,'B',36,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
            (2,'2018-08-04','2018-12-05',50,2,2018,2,'C',36,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(2,'2018-08-04','2018-12-05',50,2,2018,2,'D',36,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),

			--INSERÇÃO DICIPLINA ENGENHARIA DE SOFTWARE - ADS
			(2,'2018-08-04','2018-12-05',48,2,2018,2,'A',3,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(2,'2018-08-04','2018-12-05',48,2,2018,2,'B',3,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(2,'2018-08-04','2018-12-05',48,2,2018,2,'C',3,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(2,'2018-08-04','2018-12-05',48,2,2018,2,'D',3,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),

			--INSERÇÃO DICIPLINA GESTÃO DE PROJETOS - ADS
			(2,'2018-08-04','2018-12-05',49,2,2018,2,'A',17,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(2,'2018-08-04','2018-12-05',49,2,2018,2,'B',17,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(2,'2018-08-04','2018-12-05',49,2,2018,2,'C',17,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(2,'2018-08-04','2018-12-05',49,2,2018,2,'D',17,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),

			--INSERÇÃO DICIPLINA LIBRAS - ADS
			(2,'2018-08-04','2018-12-05',165,2,2018,2,'A',39,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(2,'2018-08-04','2018-12-05',165,2,2018,2,'B',39,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(2,'2018-08-04','2018-12-05',165,2,2018,2,'C',39,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(2,'2018-08-04','2018-12-05',165,2,2018,2,'D',39,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),

			--INSERÇÃO DICIPLINA LIGUAGEM DE PROGRAMAÇÃO II - ADS
			(2,'2018-08-04','2018-12-05',45,2,2018,2,'A',24,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(2,'2018-08-04','2018-12-05',45,2,2018,2,'B',24,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(2,'2018-08-04','2018-12-05',45,2,2018,2,'C',24,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(2,'2018-08-04','2018-12-05',45,2,2018,2,'D',24,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),

			--INSERÇÃO DICIPLINA LINGUAGEM SQL - ADS
			(2,'2018-08-04','2018-12-05',46,2,2018,2,'A',18,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(2,'2018-08-04','2018-12-05',46,2,2018,2,'B',18,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(2,'2018-08-04','2018-12-05',46,2,2018,2,'C',18,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(2,'2018-08-04','2018-12-05',46,2,2018,2,'D',18,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),

			--INSERÇÃO DICIPLINA SOCIEDADE E SUSTENTABILIDADE - ADS
			(2,'2018-08-04','2018-12-05',164,2,2018,2,'A',40,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(2,'2018-08-04','2018-12-05',164,2,2018,2,'B',40,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(2,'2018-08-04','2018-12-05',164,2,2018,2,'C',40,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(2,'2018-08-04','2018-12-05',164,2,2018,2,'D',40,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),

			--INSERÇÃO DICIPLINA TECNOLOGIA WEB - ADS
			(2,'2018-08-04','2018-12-05',47,2,2018,2,'A',4,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(2,'2018-08-04','2018-12-05',47,2,2018,2,'B',4,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(2,'2018-08-04','2018-12-05',47,2,2018,2,'C',4,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(2,'2018-08-04','2018-12-05',47,2,2018,2,'D',4,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),

	--CRUSO SI

			--INSERÇÃO DICIPLINA AMBIENTE E DESENVOLVIMENTO E OPERAÇÕES - SI
    		(4,'2018-08-04','2018-12-05',50,11,2018,2,'A',36,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(4,'2018-08-04','2018-12-05',50,11,2018,2,'B',36,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),

			--INSERÇÃO DICIPLINA ENGENHARIA DE SOFTWARE - SI
			(4,'2018-08-04','2018-12-05',48,11,2018,2,'A',3,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(4,'2018-08-04','2018-12-05',48,11,2018,2,'B',3,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),

			--INSERÇÃO DICIPLINA GESTÃO DE PROJETOS - SI
			(4,'2018-08-04','2018-12-05',49,11,2018,2,'A',17,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(4,'2018-08-04','2018-12-05',49,11,2018,2,'B',17,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			
			--INSERÇÃO DICIPLINA LIBRAS - SI
			(4,'2018-08-04','2018-12-05',165,11,2018,2,'A',39,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(4,'2018-08-04','2018-12-05',165,11,2018,2,'B',39,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			
			--INSERÇÃO DICIPLINA LIGUAGEM DE PROGRAMAÇÃO II - SI
			(4,'2018-08-04','2018-12-05',45,11,2018,2,'A',24,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(4,'2018-08-04','2018-12-05',45,11,2018,2,'B',24,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			
			--INSERÇÃO DICIPLINA LINGUAGEM SQL - SI
			(4,'2018-08-04','2018-12-05',46,11,2018,2,'A',18,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(4,'2018-08-04','2018-12-05',46,11,2018,2,'B',18,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			
			--INSERÇÃO DICIPLINA SOCIEDADE E SUSTENTABILIDADE - SI
			(4,'2018-08-04','2018-12-05',164,11,2018,2,'A',40,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(4,'2018-08-04','2018-12-05',164,11,2018,2,'B',40,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			
			--INSERÇÃO DICIPLINA TECNOLOGIA WEB - SI
			(4,'2018-08-04','2018-12-05',47,11,2018,2,'A',4,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS'),
			(4,'2018-08-04','2018-12-05',47,11,2018,2,'B',4,'METODOLOGIA','RECURSOS','CRITERIOAVALIACAO','PLANODEAULAS');
