	-- USUARIO
INSERT INTO USUARIO (LOGIN, SENHA) VALUES 
('GILSON.ALMEIDA','G1501375'),
('SEBASTIAO.RODRIGUES','S1602440'),
('VALDIR.CASTRO','V1602396'),
('LUIZ.MELO','L1701777'),
('FRANCISCO.JESUS','F1602405'),
('NELSON.MOREIRA','N1602128'),
('RAIMUNDO.MORAE','R1602230'),
('FABIO.MOURA','F1601249'),
('ANDRE.COSTA','A1701595'),
('MARCIO.BATISTA','M1601576'),
('VINICIUS.CONCEICAO','V1501550'),
('JOAO.SOUSA','J1702249'),
('ANTONIO.MAGALHAES','A1702525'),
('JOSE.MORAIS','J1501148'),
('JONATHAN.FILHO','J1502810'),
('PAULO.MELO','P1602770'),
('ALESSANDRO.DIAS','A1602697'),
('EVERTON.MARTINS','E1602173'),
('EDSON.FERNANDES','E1601713'),
('EMERSON.MENEZES','E1602326'),
('CICERO.SANTANA','C1501257'),
('MICHELE.GARCIA','M1501464'),
('DOUGLAS.XAVIER','D1502465'),
('RODRIGO.GOMES','R1502808'),
('ALEXANDRE.DIAS','A1601975'),
('MAURO.CARVALHO','M1702530'),
('EDUARDO.VIEIRA','E1602305'),
('FABRICIO.MACHADO','F1701582'),
('DANIEL.ROCHA','D1501352'),
('JEAN.NEVES','J1701910'),
('TAMIRES.CAVALCANTE','T1701166'),
('DIEGO.NETO','D1502850'),
('MARCELO.SANTOS','M1602346'),
('LEONARDO.CUNHA','L1601418'),
('ALAN.AGUIAR','A1702476'),
('ADRIANA.MACHADO','A1702619'),
('MARIA.NASCIMENTO','M1502116'),
('ANA.FARIAS','A1702648'),
('RENATA.COSTA','R1702436'),
('VERA.CARDOSO','V1602388'),
('ELIANE.MENDES','E1701548'),
('JESSICA.PEREIRA','J1502514'),
('PRISCILA.FARIAS','P1601584'),
('ROSANGELA.RIBEIRO','R1502845'),
('LUCIANA.FERREIRA','L1601609'),
('ELAINE.BRAGA','E1702717'),
('ANTONIA.FILHO','A1602719'),
('PATRICIA.MORAIS','P1601963'),
('MARIA.MORAES','M1602611'),
('CLAUDIA.MOURA','M1601449'),
('ALAN.OLIVEIRA', '12345678'),
('ALBERTO.JUNIOR', '12345678'),
('ALEXANDRE.RANGEL', '12345678'),
('ALEXANDRE.MARTINS', '12345678'),
('ALVARO.TAKEI', '12345678'),
('ANA.SANTOS', '12345678'),
('BRUNO.KALKEVICIUS', '12345678'),
('CEZAR.BELLINI', '12345678'),
('EDSON.SILVA', '12345678'),
('EDSON.TSUKIMOTO', '12345678'),
('EDUARDO.QUEIROZ', '12345678'),
('EMILIO.RESENDE', '12345678'),
('FELIPE.DIAS', '12345678'),
('FERNANDO.ZUHER', '12345678'),
('FRANCESCA.ROMANELLI', '12345678'),
('GISELDA.PEREIRA', '12345678'),
('GUILHERME.LOHMANN', '12345678'),
('GUSTAVO.FERREIRA', '12345678'),
('ILANA.CONCILIO', '12345678'),
('IZA.MELÃO', '12345678'),
('JOAO.COUTINHO', '12345678'),
('JOSE.PRADO', '12345678'),
('LEONARDO.TAKUNO', '12345678'),
('LUCAS.GONÇALVES', '12345678'),
('LUCIANO.CROCCO', '12345678'),
('MARCEL.PIRES', '12345678'),
('MARCELO.SILVA', '12345678'),
('MARCELO.TERRA', '12345678'),
('MARÇO.JEUNON', '12345678'),
('OSVALDO.TAKAI', '12345678'),
('PEDRO.PADRO', '12345678'),
('PLÍNIO.FILHO', '12345678'),
('RENATO.SANTOS', '12345678'),
('RODRIGO.PIASSI', '12345678'),
('SERGIO.BRUZETTI', '12345678'),
('VANDERSON.BOSSI', '12345678'),
('VICTOR.OLIVEIRA', '12345678'),
('VLADIMIR.CHAGAS', '12345678'),
('BRUNO.LIMA','12345678'),
('ALLAN.CARVALHO','51834538'),
('AYAO.OKAMOTO','86757519');

	-- ALUNOS
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(1,'GILSON FERNANDES ALMEIDA','gf_almeida@impacta.com.br','9234131243','1501375');

INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(2,'SEBASTIAO DE OLIVEIRA RODRIGUES','sd_rodrigues@impacta.com.br','912344321','1602440');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(3,'VALDIR GOMES DE CASTRO','vg_castro@impacta.com.br','987655687','1602396');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(4,'LUIZ CARLOS DE JESUS MELO','ld_melo@impacta.com.br','912346321','1701777');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(5,'FRANCISCO DE SOUZA JESUS','fd_jesus@impacta.com.br','948639721','1602405');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(6,'NELSON FERREIRA DE MOREIRA','nf_moreira@impacta.com.br','964823197','1602128');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(7,'RAIMUNDO VIEIRA MORAES','rv_moraes@impacta.com.br','908974231','1602230');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(8,'FABIO FERNANDES MOURA','ff_moura@impacta.com.br','980974231','1601249');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(9,'ANDRE SANTOS DE COSTA','as_costa@impacta.com.br','910897423','1701595');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(10,'MARCIO DA COSTA BATISTA','md_batista@impacta.com.br','908974123','1601576');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(11,'VINICIUS SOUZA CONCEICAO','vs_conceicao@impacta.com.br','934289743','1501650');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(12,'JOAO BATISTA ALVES DA SOUSA','ja_sousa@impacta.com.br','9417829034','1702249');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(13,'ANTONIO CARLOS FERREIRA DE MAGALHAES','af_magalhaes@impacta.com.br','981234897','1702525');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(14,'JOSE CARLOS LIMA MORAIS','jl_morais@impacta.com.br','946123879','1501148');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(15,'JONATHAN SANTOS DE FILHO','js_filho@impacta.com.br','941632789','1502810');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(16,'PAULO RODRIGUES DA MELO','pr_melo@impacta.com.br','919283476','1602770');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(17,'ALESSANDRO  DIAS','a_dias@impacta.com.br','917234908','1602697');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(18,'EVERTON DE OLIVEIRA MARTINS','ed_martins@impacta.com.br','94618279','1602173');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(19,'EDSON APARECIDA DE FERNANDES','ea_fernandes@impacta.com.br','912346789','1601713');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(20,'EMERSON GOMES MENEZES','eg_menezes@impacta.com.br','946897231','1602326');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(21,'CICERO PEREIRA DE SANTANA','cp_santana@impacta.com.br','919283674','1501257');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(22,'MICHELE SOUZA GARCIA','ms_garcia@impacta.com.br','971234897','1501464');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(23,'DOUGLAS GONCALVES XAVIER','dg_xavier@impacta.com.br','942634897','1502465');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(24,'RODRIGO REGINA GOMES','rr_gomes@impacta.com.br','912376589','1502808');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(25,'ALEXANDRE DE JESUS DIAS','ad_dias@impacta.com.br','923419686','1601975');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(26,'MAURO DE JESUS CARVALHO','md_carvalho@impacta.com.br','943621789','1702530');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(27,'EDUARDO  VIEIRA','e_vieira@impacta.com.br','942135687','1602305');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(28,'FABRICIO REGINA MACHADO','fr_machado@impacta.com.br','941236789','1701582');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(29,'DANIEL FERREIRA DE ROCHA','df_rocha@impacta.com.br','9213467859','1501352');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(30,'JEAN DA COSTA NEVES','jd_neves@impacta.com.br','941236897','1701910');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(31,'TAMIRES PEREIRA DE CAVALCANTE','tp_cavalcante@impacta.com.br','952316897','1701166');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(32,'DIEGO REGINA NETO','dr_neto@impacta.com.br','941329867','1502850');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(33,'MARCELO DOS SANTOS','md_santos@impacta.com.br','941237896','1602346');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(34,'LEONARDO RODRIGUES DE CUNHA','lr_cunha@impacta.com.br','941285896','1601418');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(35,'ALAN ALVES AGUIAR','aa_aguiar@impacta.com.br','941237588','1702476');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(36,'ADRIANA FERNANDES MACHADO','af_machado@impacta.com.br','941236879','1702619');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(37,'MARIA BARBOSA NASCIMENTO','mb_nascimento@impacta.com.br','932714189','1502116');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(38,'ANA PAULA FERREIRA DE FARIAS','af_farias@impacta.com.br','942138976','1702648');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(39,'RENATA VIEIRA COSTA','rv_costa@impacta.com.br','914237698','1702436');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(40,'VERA  CARDOSO','v_cardoso@impacta.com.br','998761234','1602388');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(41,'ELIANE BARBOSA MENDES','eb_mendes@impacta.com.br','943215787','1701548');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(42,'JESSICA DE OLIVEIRA PEREIRA','jd_pereira@impacta.com.br','942318957','1502514');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(43,'PRISCILA MARIA DE FARIAS','pm_farias@impacta.com.br','998761423','1601584');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(44,'ROSANGELA PEREIRA DE RIBEIRO','rp_ribeiro@impacta.com.br','941237967','1502845');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(45,'LUCIANA MARIA FERREIRA','lm_ferreira@impacta.com.br','943278932','1601609');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(46,'ELAINE SOARES BRAGA','es_braga@impacta.com.br','912376893','1702717');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(47,'ANTONIA FERREIRA FILHO','af_filho@impacta.com.br','923167893','1602719');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(48,'PATRICIA DE SOUZA MORAIS','pd_morais@impacta.com.br','934216789','1601963');
 
INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(49,'MARIA JOSE APARECIDA MORAES','ma_moraes@impacta.com.br','974367892','1602611');

INSERT INTO ALUNO(IDUSUARIO,NOME,EMAIL,CELULAR,RA) 
    VALUES(50,'CLAUDIA DE LIMA MOURA','cd_moura@impacta.com.br','978365892','1601449');


	-- COORDENADOR
INSERT INTO COORDENADOR (IDUSUARIO, NOME, EMAIL, CELULAR)VALUES
	(65, 'FRANCESCA ROMANELLI', 'f_romanelli@impacta.com.br','11935612587'),
	(56, 'ANA CRISTINA DOS SANTOS','ac_santos@impacta.com.br','11965325167'),
	(89, 'BRUNO LUIS SOARES DE LIMA','b_lima@impacta.com.br','11965771258'),
	(80, 'OSVALDO KOTARO TAKAI','ok_takai@impacta.com.br','11963258147'),
	(90, 'ALAN HENRIQUE PARDO DE CARVALHO','al_carvalho@impacta.com.br','11965846576'),
	(91, 'AYAO OKAMOTO', 'ay_okamoto@impacta.com.br','11968541235');

	-- CURSOS
INSERT INTO CURSO(NOME) 
    VALUES ('Administração');

INSERT INTO CURSO(NOME) 
    VALUES ('Análise e Desenvolvimento de Sistemas');

INSERT INTO CURSO(NOME) 
    VALUES ('Análise e Desenvolvimento de Sistemas EAD');

INSERT INTO CURSO(NOME) 
    VALUES ('Banco de Dados');

INSERT INTO CURSO(NOME) 
    VALUES ('Engenharia da Computação');

INSERT INTO CURSO(NOME) 
    VALUES ('Gestão de Tecnologia da Informação');

INSERT INTO CURSO(NOME) 
    VALUES ('Jogos Digitais');

INSERT INTO CURSO(NOME) 
    VALUES ('Processo Gerenciais');

INSERT INTO CURSO(NOME) 
    VALUES ('Produção de Multimídia');

INSERT INTO CURSO(NOME) 
    VALUES ('Redes de Computadores');

INSERT INTO CURSO(NOME) 
    VALUES ('Sistema de Informação');

	-- DISCIPLINA
	-- OBSERVAÇÃO!! O NOME CAMPO 'NOME' DEVE SER ALTERADO PARA VARCHAR(100), POIS HÁ MATERIAS QUE POSSUEM MAIS DE 30 CARACTERES, CASO CONTRARIO NÃO EXECUTARA -- 

	-- ADMINISTRÇÃO
INSERT INTO DISCIPLINA VALUES
	--  1SEM
	('Comunicação e Expressão', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Fundamentos da Administração', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Macroeconomia', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Matemática Aplicada', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Modelos de Negócio e Empreendedorismo', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Pensamento Crítico e Ética', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	-- 2SEM
	('Análise Exploratória de Dados', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Cálculo', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Contabilidade Financeira', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Microeconomia', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Raciocínio Analítico', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Sociologia e Política', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	-- 3SEM
	('Comportamento Organizacional', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Contabilidade Gerencial', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Gestão de Projetos e Programas', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Inteligência de Negócios', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Matemática Financeira', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Modelagem de Processos de Negócio', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	-- 4SEM
	('Administração Financeira', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Estratégia Organizacional', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Gestão de Marketing', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Gestão de Operações', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Gestão Estratégica de Pessoas', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	-- 5SEM
	('Design Thinking', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Direito Aplicado à Administração', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Gestão de Qualidade', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Marketing Avançado', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Responsabilidade Social Corporativo', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Startup e Inovação', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	-- 6SEM
	('Finanças Corporativas e Mercado de Capitais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Gestão da Cadeia de Suprimentos', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Gestão de Custos', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Gestão de Projetos de Inovação', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Tomada de Decisão e Negociação', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	-- 7SEM
	('Análise de Viabilidade de Projetos', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Estratégia Competitiva e Corporativa', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Jogos de Estratégias', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	
	-- 8SEM
	('Governança Corporativa', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Negócios Internacionais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Sistemas Integrados de Gestão', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1);
	

	-- Análise e Desenvolvimento de Sistemas
INSERT INTO DISCIPLINA VALUES
	-- 1SEM
	('Fundamentos de Banco de Dados', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Introdução à Internet das Coisas - IoT', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Linguagem de Programação I', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Lógica de Programação', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	-- 2SEM
	('Linguagem de Programação II', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Linguagem SQL', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Tecnologia Web', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Engenharia de Software', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Gestão de Projetos', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Ambiente de Desenvolvimento e Operação', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	-- 3SEM
	('Desenvolvimento de Aplicações Distribuídaso', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Estrutura de Dados', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Análise e Modelagem de Sistemas', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Engenharia de Requisitos', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Interface Homem-Computador', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	-- 4SEM
	('Arquitetura e Projeto de Sistemas', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Desenvolvimento para Dispositivos Móveis', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Desenvolvimento para Internet das Coisas', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Qualidade de Software', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Legislação e Ética', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2);

	-- Sistemas de Informação
INSERT INTO DISCIPLINA VALUES 
	-- 5SEM
	('Business Agility', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 4),
	('Desenvolvimento de Sistemas de Informação', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 4),
	('Teoria da Computação', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 4),
	-- 6SEM
	('Integração e Desenvolvimento de Sistemas', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 4),
	-- 7SEM
	('Business Intelligence', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 4),
	('Segurança e Auditoria de Sistemas', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 4),
	('Gestão de Infraestrutura de TI', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 4),
	-- 8SEM
	('Computação Cognitiva', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 4),
	('Governança de TI', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 4);

	-- Banco de Dados
INSERT INTO DISCIPLINA VALUES
	-- 2SEM
	('Desenvolvimento de Sistemas', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	-- 3SEM
	('Developing Database', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Data Analytics', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	-- 4SEM
	('Administração de Banco de Dados', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Qualidade de Governança de Dados', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Segurança de Banco de Dados', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Big Data', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2);

	-- Engenharia da Computação
INSERT INTO DISCIPLINA VALUES
	-- 1SEM
	('Circuitos Digitais e Eletrônicos', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Matemática para Engenharia', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	-- 2SEM
	('Conceitos e Aplicações de Cálculo', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	-- 3SEM
	('Ciências do Ambiente', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Desenvolvimento de Aplicações Distribuídas', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Modelagem e Simulação de Sistemas Físicos', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	-- 4SEM
	('Circuitos Elétricos', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Eletricidade e Magnetismo Aplicados', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Matemática Discreta', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Otimização de Sistemas Lineares', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	-- 5SEM
	('Análise Numérica', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Arquitetura de Computadores e Sistemas Operacionais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	-- 6SEM
	('Compiladores', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Controle e Automação', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Gestão Ágil de Projetos', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Sistemas Distribuídos e Cloud Computing', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	-- 7SEM
	('Economia para Engenharia', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Robôs Móveis Inteligentes', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Segurança Cibernética', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('UX e Design Thinking', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	-- 8SEM
	('Indústria 4.0', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Projeto de Sistemas Embarcados', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Sistemas Tolerantes a Falhas', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Tópicos Especiais em Tendências Tecnológicas', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3);

	-- Gestão da Tecnologia da Informação
INSERT INTO DISCIPLINA VALUES
	('Gestão Estratégica de TI', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 4);

	-- Jogos Digitais
INSERT INTO DISCIPLINA VALUES
	-- 
	('Desenho e Concept Art para Jogos', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Design de Jogos I', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Empreendedorismo', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Introdução aos Jogos Digitais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Arte 2D para Jogos Digitais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Arte 3D para Jogos Digitais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Design de Jogos II', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Programação para Jogos Digitais I', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Processo de Produção de Jogos Digitais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Game Level Design', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Design de Personagens para Jogos Digitais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Jogos Digitais para Web', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Programação para Jogos Digitais II', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Roteirização e Storyboard para Jogos Digitais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Animação, Áudio e Vídeo para Jogos Digitais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Estudos Complementares em Jogos Digitais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Jogos Digitais para Dispositivos Móveis', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Marketing para Jogos Digitais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5),
	('Qualidade e Testes para Jogos Digitais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 5);

	-- Processos Gerenciais
INSERT INTO DISCIPLINA VALUES
	('Modelos de Negócios e Empreendedorismo', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1);

	-- Produção Multimidia
INSERT INTO DISCIPLINA VALUES
	('Teoria da Cor', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Filosofia', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Processo Criativo', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Storytelling', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Tipografia', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Computação Gráfica', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Fotografia Digital', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Gamificação', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Novas Mídias', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Marketing Digital e Mídias Sociais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Criação e Produção Web', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Design de Informação', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Direção de Arte', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Modelagem 3D', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Produção Audiovisual', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Aplicativo Mobile', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Cibercultura', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Linguagem Sonora', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6),
	('Efeitos Especiais', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 6);

	-- Redes de Computadores
INSERT INTO DISCIPLINA VALUES
	('Administração de Redes e Sistemas', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Cabeamento Estruturado:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Arquitetura de Redes de Computadores:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Fundamentos de Sistemas Operacionais:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Programação para Redes:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Administração de Redes e Sistemas Operacionais Livres:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Redes de Longa Distância:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Routing:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Segurança em Redes e Infraestrutura:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Comunicação de Dados:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Diagnóstico e Gerenciamento de Redes:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Redes Convergentes:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Segurança em Sistemas:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Switching:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Computação em Nuvem:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Comunicações Móveis:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Auditoria e Controle de TI:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Redes IPV6:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Serviços de Redes de Computadores:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3),
	('Tópicos Especiais em Redes de Computadores:', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 3);

	-- Outros
INSERT INTO DISCIPLINA VALUES
	('OPE1 - Oficina Projeto Empresa 1', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('OPE2 - Oficina Projeto Empresa 2', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('OPE3 - Oficina Projeto Empresa 3', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 2),
	('Sociedade e Sustentabilidade - Optativa', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Linguagem Brasileira de Sinais - LIBRAS', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 40,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Trabalho de Conclusão de Curso 1 - TCC1', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1),
	('Trabalho de Conclusão de Curso 2 - TCC2', GETDATE(), 'ABERTA', 'PLANODE ENSINO', 80,'COMPETENCIAS', 'HABILIDADES', 'EMENTA', 'CONTEUDO PROGRAMATICO', 'BIBLIOGRAFIA BASICA', 'BIBLIOGRAFIA COMPLEMENTAR', 50, 50, 1);

