
INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(51,'ALAN ALVES DE OLIVEIRA','aa_oliveira@impacta.com.br','912345678','ALAN ')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	  VALUES(52,'ALBERTO DE MEDEIROS JUNIOR','am_junior@impacta.com.br','923845967', 'ALBERTO')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(53,'ALEXANDRE LEITE RANGEL','al_rangel@impacta.com.br','943829748', 'RANGEL')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(54,'ALEXANDRE LOCCI MARTINS','al_martins@impacta.com.br','957394928','MARTINS')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(55,'ALVARO TOSHIO TAKEI','at_takei@impacta.com.br','947284927', 'ALVARO')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(56,'ANA CRISTINA DOS SANTOS','ac_santos@impacta.com.br','943829347','ANA ')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(57,'BRUNO ROBERTO KALKEVICIUS','br_kalkevicius@impacta.com.br','958329475', 'BRUNO')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(58,'CEZAR BELLINI','c_bellini@impacta.com.br','918475385', ' CEZAR')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(59,'EDSON BENITES SILVA','eb_silva@impacta.com.br','968492045', 'EDSON ')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(60,' EDSON TIHARU TSUKIMOTO','et_tsukimoto@impacta.com.br ',' 967894567', ' TSUKIMOTO')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(61,' EDUARDO LUIS DE QUEIROZ','el_queiroz@impacta.com.br ','978394756', ' EDU')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(62,' EMILIO MURTA RESENDE',' em_resende@impacta.com.br','934586923 ', 'EMILIO ')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(63,' FELIPE AUGUSTO ROCHA DIAS','fa_dias@impacta.com.br ','988334495 ', 'FELIPE ')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(64,' FERNANDO ZUHER','f_zuher@impacta.com.br ',' 974938540', 'FERNANDO ')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(65,'FRANCESCA ROMANELLI ','f_romanelli@impacta.com.br ','984726485 ', ' FRANCESCA')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(66,'GISELDA FERNANDA PEREIRA ','gf_pereira@impacta.com.br ','997840597', ' GISELDA')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(67,'GUILHERME GARCEZ LOHMANN ',' gg_lohmann@impacta.com.br','989485725 ', 'GUILHERME ')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(68,'GUSTAVO MENDES FERREIRA ',' gm_ferreira@impacta.com.br','909485736 ', 'FERREIRA ')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(69,'ILANA DE ALMEIDA SOUZA CONCILIO ',' ia_concilio@impacta.com.br','984756349 ', ' ILANA')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(70,' IZA MELÃO',' i_melão@impacta.com.br',' 985736450', ' IZA')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(71,' JOÃO PAULO VENÂNCIO COUTINHO','jp_coutinho@impacta.com.br ','9485722645 ', ' JP')
	 
	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(72,'JOSÉ PACHECO DE ALMEIDA PRADO',' jp_prado@impacta.com.br','995403900 ', ' PACHECO')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(73,'LEONARDO MASSAYUKI TAKUNO ',' lm_takuno@impacta.com.br','950693847 ', ' TAKUNO')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(74,' LUCAS MENDES MARQUES GONÇALVES',' lm_gonçalves@impacta.com.br','995006798 ', 'LUCAS ')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(75,' LUCIANO CROCCO','l_crocco@impacta.com.br ','955683499 ', 'LUCIANO ')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,EMAIL,CELULAR,APELIDO)
	 VALUES(76,'MARCEL GINOTTI PIRES ',' mg_pires@impacta.com.br',' 945069405', ' MARCEL')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,CELULAR,APELIDO)
	 VALUES(77,'MARCELO CORREIA DA SILVA','mc_silva@impacta.com.br','905948350','MARCELO')
	 
	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,CELULAR,APELIDO)
	 VALUES(78,'MARCELO SANSINI TERRA','ms_terra@impacta.com.br','909584739','SANSINI')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,CELULAR,APELIDO)
	 VALUES(79,'MARCO TÚLIO JEUNON','mt_jeunon@impacta.com.br','900948573','MARCO')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,CELULAR,APELIDO)
	 VALUES(80,'OSVALDO KOTARO TAKAI','ok_takai@impacta.com.br','958437567','TAKAI')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,CELULAR,APELIDO)
	 VALUES(81,'PEDRO FELIPE DO PRADO','pf_prado@impacta.com.br','905968374','PEDRO')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,CELULAR,APELIDO)
	 VALUES(82,'PLÍNIO BARBIERI FILHO','pb_filho@impacta.com.br','940583277','PLINIO')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,CELULAR,APELIDO)
	 VALUES(83,'RENATO DE SOUZA SANTOS','rs_santos@impacta.com.br','940593845','RENATO')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,CELULAR,APELIDO)
	 VALUES(84,'RODRIGO PIASSI','r_piassi@impacta.com.br','905943849','RODRIGO')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,CELULAR,APELIDO)
	 VALUES(85,'SÉRGIO EDUARDO DI SANTORO BRUZETTI','se_bruzetti@impacta.com.br','999504958','SÉRGIO')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,CELULAR,APELIDO)
	 VALUES(86,'VANDERSON GOMES BOSSI','vg_bossi@impacta.com.br','998574634','VANDERSON')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,CELULAR,APELIDO)
	 VALUES(87,'VICTOR INÁCIO DE OLIVEIRA','vi_oliveira@impacta.com.br','958439846','VICTOR')

	 INSERT INTO PROFESSOR (IDUSUARIO,NOME,CELULAR,APELIDO)
	 VALUES(88,'VLADIMIR CHAGAS','v_chagas@impacta.com.br','905846372','VLADIMIR')