CREATE DATABASE BD_PROJETO_7_8
USE BD_PROJETO_7_8
CREATE TABLE CURSO
(
	ID INT IDENTITY,--(PK)
	NOME VARCHAR (200) NOT NULL,--(UQ)
	CONSTRAINT PK_ID_CURSO PRIMARY KEY (ID)
);
CREATE TABLE SOLICITACAO_MATRICULA
(
	ID INT IDENTITY,--(PK)
	ID_ALUNO TINYINT NOT NULL,--(FK)
	ID_DISCIPLINA_OFERTADA CHAR (40) NOT NULL,--(FK)
	ID_SOLICITACAO DATETIME NOT NULL DEFAULT GETDATE(),--(DF)
	ID_CORDENADOR TINYINT,--(FK)
	STATUS CHAR(20) DEFAULT 'Solicitado',--(DF,CK)
	CONSTRAINT PK_ID_SOLICITACAO_MATRICULA PRIMARY KEY (ID),
	--(CONSTRAINT FK_ID_SOLICITACAO_MATRICULA FOREING KEY (ID_ALUNO) REFERENCES ALUNO (ID))
	--(CONSTRAINT FK_ID_SOLICITACAO_MATRICULA FOREING KAY (ID_DISCIPLINA_OFERTADA) REFERENCES DisciplinaOfertada (ID))
	--(CONSTRAINT FK_ID_SOLICITACAO_MATRICULA FOREING KAY (ID_CORDENADOR) REFERENCES CORDENADOR (ID))
	CONSTRAINT CK_STATUS CHECK (STATUS IN ('Solicitada','Aprovada','Rejeitada','Cancelada'))
);
