CREATE DATABASE BD_PROJETO_7_8
USE BD_PROJETO_7_8
CREATE TABLE CURSO
(
	ID INT IDENTITY,--(PK)
	NOME CHAR (30) NOT NULL,--(UQ)
	CONSTRAINT PK_ID_CURSO PRIMARY KEY (ID)
);
CREATE TABLE SOLICITACAO_MATRICULA
(
	ID INT IDENTITY,--(PK)
	ID_ALUNO TINYINT NOT NULL,--(FK)
	ID_DISCIPLINA_OFERTADA CHAR (40) NOT NULL,--(FK)
	DT_SOLICITACAO DATE NOT NULL,--(DF)
	ID_CORDENADOR TINYINT,--(FK)
	STATUS CHAR(20),--(DF,CK)
	CONSTRAINT PK_ID_SOLICITACAO_MATRICULA PRIMARY KEY (ID)
);