CREATE TABLE ALUNO(
	ID INT IDENTITY  (1,1) PRIMARY KEY NOT NULL ,
	NOME VARCHAR (50) NOT NULL ,
	EMAIL VARCHAR (30) UNIQUE NOT NULL,
	CELULAR VARCHAR(15) UNIQUE NOT NULL,
	RA VARCHAR (10) UNIQUE NOT NULL,
	FOTO VARCHAR(500),
	
);

CREATE TABLE PROFESSOR(
	ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	EMAIL VARCHAR (30) UNIQUE NOT NULL,
	CELULAR VARCHAR(15) UNIQUE NOT NULL,
	APELIDO VARCHAR (20) NOT NULL,
	
);